workflows:
  ios-workflow:
    name: iOS Build (IPA + TestFlight)

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      groups:
        - certificate_credentials   # 👈 THIS IS THE FIX

      ios_signing:
        distribution_type: app_store
        bundle_identifier: de.digicarepro.employee

    integrations:
      app_store_connect: DigiCarePro

    triggering:
      events:
        - push

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Clean iOS build
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          cd ..

      - name: Build IPA
        script: flutter build ipa

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
