// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB741x4g7kFAGgfwUFRJzjk1M7azbcnqRk',
    appId: '1:52634179125:web:8423b75c6597ce3cf1837c',
    messagingSenderId: '52634179125',
    projectId: 'digicarepro-ec445',
    authDomain: 'digicarepro-ec445.firebaseapp.com',
    storageBucket: 'digicarepro-ec445.firebasestorage.app',
    measurementId: 'G-HJ1CGP41JT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIWqyOMXKPBz6zed42ZasYuDsSeL7Ns04',
    appId: '1:52634179125:android:a1b14a8cdf1dc633f1837c',
    messagingSenderId: '52634179125',
    projectId: 'digicarepro-ec445',
    storageBucket: 'digicarepro-ec445.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfUMxPQ-AOnUHcZoucnpbUThsunDR_RPs',
    appId: '1:52634179125:ios:e1475c010b34f0aaf1837c',
    messagingSenderId: '52634179125',
    projectId: 'digicarepro-ec445',
    storageBucket: 'digicarepro-ec445.firebasestorage.app',
    iosBundleId: 'de.digicarepro.employee',
  );
}
